services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    ports:
      - "80:80"
    container_name: app
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./_docker/env/postgre.env
    ports:
      - "5432:5432"
    container_name: app_db
  redis:
    image: redis:7.2
    volumes:
      - ./tmp/redis:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6380:6379'
    restart: always
    container_name: app_redis

  rabbitmq:
    image: rabbitmq:4.1.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./tmp/rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./_docker/env/rabbitmq.env
    container_name: app_rabbitmq

  worker:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    command: php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90
    env_file:
      - ./_docker/env/postgre.env
      - ./_docker/env/rabbitmq.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    container_name: app_worker

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    container_name: app_mailhoog
